# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDSD():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_dSD(self):
        self.driver.get("https://youcare.world/all?q=Antena+3&o=0")
        self.driver.set_window_size(1105, 1009)
        self.driver.find_element(By.LINK_TEXT, "Antena 3 - Specialiști în știri").click()
        self.driver.execute_script("window.scrollTo(0,159)")
        self.driver.find_element(By.CSS_SELECTOR, ".base-header__first-line").click()
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").send_keys("Stirileprotv")
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").send_keys(Keys.ENTER)
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.LINK_TEXT, "Pune Ştirile PRO TV în browser - Descarcă Opera gratis").click()
        self.driver.switch_to.default_content()
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").send_keys(Keys.ENTER)
        self.driver.find_element(By.LINK_TEXT, "stirileprotv.ro › international").click()
        self.driver.execute_script("window.scrollTo(0,125)")
        self.driver.find_element(By.CSS_SELECTOR, "html").click()
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").send_keys("Digi")
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").send_keys(Keys.ENTER)
        element = self.driver.find_element(By.CSS_SELECTOR, ".base-header__icon img")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.LINK_TEXT, "Digi International - Industrial IoT (IIoT) Devices and…").click()
        self.driver.find_element(By.CSS_SELECTOR, ".base-header__first-line").click()
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").send_keys("Common Good")
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").send_keys(Keys.ENTER)
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.LINK_TEXT, "The Common Good - Search On Our Website").click()
        self.driver.switch_to.default_content()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.LINK_TEXT, "The Common Good - Harvard University").click()
        self.vars["win2185"] = self.wait_for_window(2000)
        self.vars["root"] = self.driver.current_window_handle
        self.driver.switch_to.window(self.vars["win2185"])
        self.driver.close()
        self.driver.switch_to.window(self.vars["root"])
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.LINK_TEXT, "THE COMMON GOOD - IESE Business School").click()
        self.vars["win9297"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win9297"])
        self.driver.close()
        self.driver.switch_to.window(self.vars["root"])
        self.driver.execute_script("window.scrollTo(0,91)")
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").send_keys("Common Goods")
        self.driver.find_element(By.CSS_SELECTOR, ".search-bar__input").send_keys(Keys.ENTER)

        